### ISSUE TITLE
通道问题

### ISSUE THREAD

**Issue by ybinliu** [CocaineCong/micro-todoList#14]
在app/task/repository/mq/task文件下的task_sync.go 中关于forever通道只使用了var声明，而最后直接取值，这部分有问题吗？

**Comment by tsingfa** [comment]
自动回复邮件已经收到啦，我会尽快处理。:)

**Comment by CocaineCong** [comment]
> 在app/task/repository/mq/task文件下的task_sync.go 中关于forever通道只使用了var声明，而最后直接取值，这部分有问题吗？

这是用来阻塞主进程的，有什么问题吗？

**Comment by ybinliu** [comment]
不make初始化也是可以用来阻塞主进程吗？感谢解答。
